try {
    throw Exception.new("Test");
    out("c-0");
} catch (err) {
    out(err.message);
}
